name: MultiArch Build
on:
  push:
    branches:
      - 'main'
jobs:
  build-app:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      id-token: write
      contents: read
    env:
      DOCKER_IMAGE_NAME: dummy
      ECR_IMAGE_NAME: t3-dummy
      AWS_REGION: us-east-1
      ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/CICD_ECR
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2

      - name: setup
        run: |
          mv ./docker/build.Dockerfile ./Dockerfile 
          mkdir build

      - name: build utility image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: build app
        run: docker run --name ${{ env.DOCKER_IMAGE_NAME }}-build ${{ env.DOCKER_IMAGE_NAME }}

      - name: extract build
        run: |
          docker cp ${{ env.DOCKER_IMAGE_NAME }}-build:/app/.next ./build
          docker cp ${{ env.DOCKER_IMAGE_NAME }}-build:/app/node_modules ./build

      - name: setup build
        run: |
          mv ./docker/run.Dockerfile ./build/Dockerfile
          mv public next.config.mjs package.json ./build

      - name: cleanup build
        run: |
          docker rm ${{ env.DOCKER_IMAGE_NAME }}-build
          docker rmi ${{ env.DOCKER_IMAGE_NAME }}

      - run: cd build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     path: ./build        

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}
          tags: |
            type=raw,value=linux-amd64-${{ github.run_number }}
    
      - uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
  
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: cleanup buildx
        run: |
          docker buildx rm
          docker rmi ${{ steps.meta.outputs.tags }}

      - name: Docker meta
        id: meta-arm
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}
          tags: |
            type=raw,value=linux-arm64-${{ github.run_number }}

      - uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta-arm.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: create manifest
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}:linux-arm64-${{ github.run_number }}
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}:linux-amd64-${{ github.run_number }}
          docker manifest create ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}:${{ github.run_number }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}:linux-arm64-${{ github.run_number }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}:linux-amd64-${{ github.run_number }}
          docker manifest push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_IMAGE_NAME }}:${{ github.run_number }}